services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  # clear-db:
  #   image: mysql:8.0
  #   command: sh -c "mysql -h mysql -u root -psecret -e 'USE todos; TRUNCATE TABLE todo_items;'"
  #   depends_on:
  #     - mysql

volumes:
  todo-mysql-data:
